### ISSUE TITLE
json_file_store

### ISSUE THREAD

**Issue by CaffGeek** [colestrode/skellington#15]
This doesn't seem to work, as it doesn't appear you are passing all config from the skellington constructor into the botkit constructor

**Comment by colestrode** [comment]
Nice catch! I just ran into this myself... the branch I'm working on now should add json file store along with some nice Slack app support 😄

**Comment by colestrode** [comment]
I just found out about the `stats_optout` option in 0.4.0... Stats collection leaves me a bit uneasy (and may not be kosher for some organizations), so I'm going to change the option strategy in skellington to pass the whole config (minus skellington specific ones) to Botkit. That will ensure that new options will get passed through to Botkit without requiring a PR to skellington.

**Comment by CaffGeek** [comment]
Sounds good, that's the way I would have implemented it.
