### ISSUE TITLE
[Feature] Support for multiple teams

### ISSUE THREAD

**Issue by malonehedges** [colestrode/skellington#3]
Currently this is setup to use a Slack Token and connect to one team. Are there any plans to support multiple teams?

**Comment by colestrode** [comment]
I think that's a great idea. I haven't set up a multi-team bot before, would you be open to helping out? Or talking out the approach?

**Comment by malonehedges** [comment]
For sure! I actually whipped something together yesterday. It can't be used exactly like skellington but it has the multi-bot features.

See [this gist](https://gist.github.com/malonehedges/7d10a8ca392b26ad179e89ffa7fa9712). Note the `bot` variable and the `trackBot` function. Also, the `startRTM` and `setupController` have additional logic.

**Comment by malonehedges** [comment]
Basically it comes down to storing the teams you have access to with some storage adapter and then connecting and keeping track of the teams you're connected to. I got some of the implementation from the multi-bot example on the botkit repo.

**Comment by colestrode** [comment]
Awesome! Thanks man :) I've got a good sized project atm, but I'll circle back on this in the next week or so. Feel free to take a stab at it if you don't wanna wait that long :)

**Comment by colestrode** [comment]
Some implementation notes: 
 * plugins should be able to register scopes
 * users should specify a `slackToken` OR a (`clientId`, `clientSecret`, `redirectUri`) tuple in the initialization config. If either are missing, or if the tuple is incomplete, Skellington should throw an informative error message. 
 * I'm thinking to drop support for the auto-detecting of env vars for the slackToken to keep things straightforward.
 * skellington will need to register a `create_bot` listener and manage connected bots
 * in the `rtm_close` handler, we're using a scoped bot, we should to use the bot passed to the event handler callback.
 * will need to rework how the help listeners are registered

**Comment by colestrode** [comment]
I've been doing some testing and I think I have everything working. I just need to (re)write some unit tests and then I'll create a PR.

**Comment by colestrode** [comment]
@malonehedges I merged down the multi-team-for-real branch into a new 1.0.0-wip branch. I'm going to give some time to the readme this weekend and then publish a beta version of 1.0.0 to npm soon. Let me know if you have any feed back 🙂

**Comment by malonehedges** [comment]
Looking great! 😃

**Comment by colestrode** [comment]
I just updated the readme and published a 1.0.0-beta.1. I published it under a `beta` tag so you can install it with `npm install skellington@beta`. I'll keep using that tag until I'm ready to publish 1.0.0.

Feel free to bang on it and file any issues you see 😸
